CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number INTEGER NOT NULL UNIQUE,
    patent VARCHAR(30) NOT NULL,
    description VARCHAR(255) NOT NULL,
    service TEXT NOT NULL,
    status VARCHAR(30) NOT NULL,
    payment_status VARCHAR(30) NOT NULL,
    bay_id INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    box_started_at TIMESTAMP WITH TIME ZONE,
    box_timer_started_at TIMESTAMP WITH TIME ZONE,
    box_ended_at TIMESTAMP WITH TIME ZONE,
    box_elapsed_ms BIGINT NOT NULL DEFAULT 0,
    reset_box_timer_on_next_assignment BOOLEAN NOT NULL DEFAULT FALSE,
    pending_work_detail TEXT
);

CREATE INDEX idx_vehicles_status ON vehicles (status);
CREATE INDEX idx_vehicles_bay_id ON vehicles (bay_id);
CREATE INDEX idx_vehicles_ticket_number ON vehicles (ticket_number);

CREATE TABLE vehicle_assigned_operators (
    vehicle_id BIGINT NOT NULL REFERENCES vehicles (id) ON DELETE CASCADE,
    operator_name VARCHAR(80) NOT NULL,
    operator_order INTEGER NOT NULL,
    PRIMARY KEY (vehicle_id, operator_order)
);
